# Code generated by protoc-gen-async_grpc_ruby 1.3.0, DO NOT EDIT.
require 'async/grpc'
require_relative 'hello_pb.rb'

module Helloworld
  class GreeterService
    include Async::GRPC::Service
    package 'helloworld'
    service 'Greeter'
    rpc :SayHello, HelloRequest, HelloReply, :ruby_method => :say_hello
  end

end
